"""SIM-3040: the live ROS graph's metrics match `tests/golden/baseline.json`.

`tests/golden/baseline.json` is generated by `sim/rollout.py`'s ROS-free,
GPU-backed harness (see the plan's D24) — a different pipeline from the one
this test drives (the full `racing_bringup` launch, CPU-backed JAX in `dev`).
Two fields are expected, structural differences between the two pipelines,
not regressions, so they are compared against what this pipeline is actually
configured to produce rather than the golden's own values:

- `source`: `"headless_sim"` in the golden vs. `racing_metrics`'s own
  hard-coded `metrics_source` (see `racing_metrics/src/node.cpp`).
- `track_version`: a SHA-256 of the canonical track file in the golden vs.
  this pipeline's configured `track_version` parameter, a plain version
  string (`config/vehicles/f1tenth_default.yaml`).

Everything else is compared on `scripts/compare_metrics.py`'s ordinary
tolerances. Two pipelines integrating the same physics from the same seed
have no licence to disagree by more than measurement sampling, and widening
these to absorb a difference is how a golden becomes a rubber stamp. An
earlier version of this test *did* widen them, to absorb a seed-42 lap taking
22.85s through `sim/rollout.py` but 11.31s here; the cause turned out to be
`racing_metrics` defaulting its lap distance to a hard-coded 31.4159 m —
roughly half the analytic circle's real 61.23 m centerline — so it called
half a lap a lap. It now reads the length from the canonical track.
"""

import json
from pathlib import Path

from racing_test_keywords.scenario_runner import run_scenario

from scripts.compare_metrics import compare_metrics, format_report

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
GOLDEN_PATH = REPOSITORY_ROOT / "tests" / "golden" / "baseline.json"

# racing_metrics/src/node.cpp: metrics_source
ROS_METRICS_SOURCE = "racing_metrics"
# config/vehicles/f1tenth_default.yaml: racing_metrics.track_version
ROS_TRACK_VERSION = "analytic_circle-v1"


def test_sim_3040_metrics_match_golden() -> None:
    golden = json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))
    expected = dict(
        golden,
        source=ROS_METRICS_SOURCE,
        track_version=ROS_TRACK_VERSION,
    )

    actual = run_scenario(seed=expected["seed"])

    differences = compare_metrics(expected, actual)

    assert differences == [], format_report(expected, actual, differences)
